name: CI for Streamlit App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test/test_hello.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit
      env:
        STREAMLIT_APP: hello.py
        STREAMLIT_SERVER_ADDRESS: '0.0.0.0'
        STREAMLIT_SERVER_PORT: '8501'
      run: |
        streamlit run $STREAMLIT_APP --server.address $STREAMLIT_SERVER_ADDRESS --server.port $STREAMLIT_SERVER_PORT